const appConstant = {
  GET_COMPANY_DETAIL: 'GET_COMPANY_DETAIL',
  GET_COMPANY_REQUEST: 'GET_COMPANY_REQUEST',
  GET_COMPANY_OFFICE: 'GET_COMPANY_OFFICE',
  UPDATE_HEAD: 'UPDATE_HEAD',
  ADD_COMPANY: 'ADD_COMPANY'
};

export default appConstant;
